// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxdcxjagyrpdulprblxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4ZGN4amFneXJwZHVscHJibHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTExMTEsImV4cCI6MjA1OTY2NzExMX0.ofyPFsZx4YZ0yQYa0yUYJ1MdRlJ6OdldSgFSnZQqcGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);